config/routes.rb
Fusionpanel::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'main#index'

	post 'sendmessage' => 'frontpage#sendmessage', as: 'sendmessage'
	
  get 'adduser' => 'admin#add_user', as: :add_user
  post 'adduser' => 'admin#create_user', as: :create_user

  get ':mainslug' => 'main#router', as: 'admin'
  get ':mainslug/visitorinfo/:filter_type' => 'main#visitor_info', as: 'admin_visitor_info'
  get ':mainslug/login' => 'main#router', as: 'admin_index'
  post ':mainslug/login' => 'admin#login_connect', as: 'login_connect'
  get ':mainslug/logout' => 'admin#logout', as: 'admin_logout'
	get ':mainslug/resetpassword' => 'main#resetpassword', as: 'admin_resetpassword_user'
	post ':mainslug/resetpassword' => 'main#resetpassword_submit', as: 'admin_resetpassword_submit_user'
	
  get ':mainslug/pages' => 'pages#index', as: 'admin_page'
  get ':mainslug/pages/add' => 'pages#add', as: 'admin_add_page'
  post ':mainslug/pages/add' => 'pages#create', as: 'admin_create_page'
  get ':mainslug/pages/edit/:id' => 'pages#edit', as: 'admin_edit_page'
  post ':mainslug/pages/edit/:id' => 'pages#update', as: 'admin_update_page'
  post ':mainslug/pages/delete' => 'pages#delete', as: 'admin_delete_page'

  get ':mainslug/categories' => 'categories#index', as: 'admin_category'
  post ':mainslug/categories/add' => 'categories#create', as: 'admin_create_category'
  post ':mainslug/categories/delete' => 'categories#delete', as: 'admin_delete_category'
  get ':mainslug/categories/edit/:id' => 'categories#edit', as: 'admin_edit_category'
  post ':mainslug/categories/edit/:id' => 'categories#update', as: 'admin_update_category'

  get ':mainslug/users' => 'users#index', as: 'admin_user'
  post ':mainslug/users/add' => 'users#add', as: 'admin_add_user'
  get ':mainslug/create-account/:token' => 'users#create_account', as: 'admin_createaccount_user'
  get ':mainslug/users/role' => 'users#role_index', as: 'admin_user_role'
  get ':mainslug/users/role/add' => 'users#add_role', as: 'admin_user_addrole'
  post ':mainslug/users/role/add' => 'users#create_role', as: 'admin_user_createrole'
  get ':mainslug/users/role/edit/:id' => 'users#edit_role', as: 'admin_user_editrole'
  post ':mainslug/users/role/edit/:id' => 'users#update_role', as: 'admin_user_updatetrole'
  post ':mainslug/users/role/delete' => 'users#delete_role', as: 'admin_delete_role'
  get ':mainslug/users/:username' => 'users#profile', as: 'admin_user_profile'
  post ':mainslug/create-account/:token' => 'users#create', as: 'admin_create_user'
  post ':mainslug/users/changerole' => 'users#changerole', as: 'admin_changerole_user'
  post ':mainslug/users/delete' => 'users#delete', as: 'admin_delete_user'
  post ':mainslug/users/changepassword' => 'users#changepassword', as: 'admin_changepassword_user'
  post ':mainslug/users/forgotpassword' => 'main#forgotpassword', as: 'admin_forgotpassword_user'
  
  get ':mainslug/widgets' => 'widgets#index', as: 'admin_widget'
  get ':mainslug/widgets/add' => 'widgets#add', as: 'admin_add_widget'
  post ':mainslug/widgets/add' => 'widgets#create', as: 'admin_create_widget'
  post ':mainslug/widgets/delete' => 'widgets#delete', as: 'admin_delete_widget'
  get ':mainslug/widgets/edit/:id' => 'widgets#edit', as: 'admin_edit_widget'
  post ':mainslug/widgets/edit/:id' => 'widgets#update', as: 'admin_update_widget'

  get ':mainslug/assets' => 'assets#index', as: 'admin_asset'
  get ':mainslug/file_writer/:file_id' => 'assets#file_writer', as: 'admin_asset_filewriter'
  get ':mainslug/template_loader' => 'assets#template_loader', as: 'admin_asset_templateloader'
  post ':mainslug/assets/upload' => 'assets#upload', as: 'admin_assets_upload'
  post ':mainslug/assets/create_dir' => 'assets#create_dir', as: 'admin_assets_create_dir'
  get ':mainslug/assets/edit/:file_id' => 'assets#edit_file', as: 'admin_asset_edit_file'
  post ':mainslug/assets/edit/:file_id' => 'assets#update_file', as: 'admin_asset_update_file'
  get ':mainslug/assets/download/:file_id' => 'assets#download', as: 'admin_asset_download'
  post ':mainslug/assets/delete' => 'assets#delete', as: 'admin_asset_delete'

  get ':mainslug/settings' => 'settings#index', as: 'admin_setting'
  post ':mainslug/settings/update' => 'settings#update', as: 'admin_setting_update'
  post ':mainslug/settings/updatepage' => 'settings#updatepage', as: 'admin_setting_updatepage'
  post ':mainslug/settings/updatesmtp' => 'settings#update_smtp', as: 'admin_setting_updatesmtp'
  
  get ':mainslug/templates' => 'templates#index', as: 'admin_template'
  get ':mainslug/templates/add' => 'templates#add', as: 'admin_add_template'
  post ':mainslug/templates/create' => 'templates#create', as: 'admin_create_template'
  post ':mainslug/templates/delete' => 'templates#delete', as: 'admin_delete_template'
  get ':mainslug/templates/edit/:id' => 'templates#edit', as: 'admin_edit_template'
  post ':mainslug/templates/edit/:id' => 'templates#update', as: 'admin_update_template'

  get ':mainslug/webtraffic' => 'webtraffic#index', as: 'admin_webtraffic'
  get ':mainslug/webtraffic/:id' => 'webtraffic#details', as: 'admin_webtraffic_details'
  
  get ':mainslug/adminactivities' => 'adminactivities#index', as: 'admin_adminactivities'
  
  get ':mainslug/about' => 'about#index', as: 'admin_about'
  
  get '*pagecats/:page' => 'frontpage#index', as: 'frontendpage'
  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :page, :foreign_key => 'created_by'
  belongs_to :role
  has_many :activity

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :fullname, presence: true
  validates :crypted_password, presence: true
  validates :crypted_password, confirmation: true

  validates :username, length: { in: 6..20 }, :allow_blank => true
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }, :allow_blank => true
  validates :crypted_password, length: { minimum: 8 }, :allow_blank => true

  before_create :encrypt_password
  
  PERMISSION_ERROR_MSG = "You don't have permission to perform this action."
  
  def self.login(username, password)
    user = find(:first, :conditions => ['email = ? or username = ?', username, username])
    if user && user.crypted_password == BCrypt::Engine.hash_secret(password, user.password_salt)
    user
    else
      nil
    end
  end

  def encrypt_password
    if crypted_password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.crypted_password = BCrypt::Engine.hash_secret(crypted_password, password_salt)
    end
  end

  def self.search(query)
    if query
      if User.where('fullname LIKE ?', "%#{query}%").take
        where('fullname LIKE ?', "%#{query}%")
      else
        if User.where('username LIKE ?', "%#{query}%").take
          where('username LIKE ?', "%#{query}%")
        else
          where('email LIKE ?', "%#{query}%")
        end
      end
    else
      all
    end 
  end

  def date_joined
    self.created_at.to_time.strftime('%b %d, %Y')
  end

  def username
    self.read_attribute(:username)
  end

end

app/views/admin/pages/add.html.erb
<div class="btn-group">
	<a href="<%= admin_page_path %>" class="btn"><i class="icon-file"></i> Back to Pages</a>
</div>
<div class="row-fluid">
	<div class="span4">
		<h1>Create New Page</h1>
	</div>
	<div class="span8">
		<div class="pull-right">
			<div class="btn-holder margin0">
				<a href="<%= admin_page_path %>" class="btn btn-large pull-right">Cancel</a>
				<a href="javascript:void(0)" class="btn btn-primary btn-large mr5 pull-right" onclick="create_new_page.submit();">Save</a>
			</div>
		</div>
	</div>
</div>
<% if flash[:error] %>
<div class="alert alert-error">
	<button type="button" class="close" data-dismiss="alert">
        x
    </button>
	<% flash[:error].each do |error_message| %>
	<%= error_message %>
	<br />
	<% end %>
</div>
<% end %>
<%= form_for :page, url: admin_create_page_path, :html => {:name => 'create_new_page'}  do |page_form| %>
<span class="input_label">Content Title</span>

<%= page_form.text_field :content_title, :class=>"input-block-level", "ng-model"=>"pageTitle", "ng-change"=>"populateSlug()", "ng-init"=>"pageTitle='"+@params_content_title+"'" %>
<div class="container-fluid nopadding">
	<div class="row-fluid">
		<div class="span4">
			<span class="input_label">URL Slug</span><%= page_form.text_field :url_slug, :class=>"input-block-level", "ng-model"=>"pageSlug", "ng-init"=>"pageSlug='"+@params_url_slug+"'" %>
		</div>
		<div class="span3">
			<span class="input_label">Page Category</span>
			<%= page_form.hidden_field :category_id, :class=>"category_id", :value=>"{{categoryValue}}", "ng-init"=>"categoryValue='"+@params_category+"'" %>
			<div class="btn-group mb10">
				<a href="javascript:void(0)" class="btn btn-cat btn-large w155 fsize14">{{categoryValue}}</a>
				<button data-toggle="dropdown" class="btn btn-large dropdown-toggle">
					<span class="caret"></span>
				</button>
				<ul class="dropdown-menu category-menu">
					<% @categories.each do |category| %>
					<li>
						<a href="" ng-click="selectCategory('<%= category.name %>')"><%= category.name %></a>
					</li>
					<% end %>
					<li class="divider"></li>
					<li>
						<a href="">No Category</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="span2">
			<span class="input_label">Page Status</span>
			<%= page_form.hidden_field :status, :class=>"status", :value=>"{{statusValue.toLowerCase()}}", "ng-init"=>"statusValue='"+@params_page_status+"'" %>
			<div class="btn-group mb10">
				<a href="javascript:void(0)" class="btn btn-stat btn-large w75 fsize14">{{statusValue}}</a>
				<button data-toggle="dropdown" class="btn btn-large dropdown-toggle">
					<span class="caret"></span>
				</button>
				<ul class="dropdown-menu status-menu">
					<li>
						<a href="" ng-click="selectStatus('Active')">Active</a>
					</li>
					<li>
						<a href="" ng-click="selectStatus('Inactive')">Inactive</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="span3">
            <span class="input_label">Page Template</span>
            <input type="hidden" name="template_value" value="{{templateValue}}" ng-init="templateValue='<%= @params_template_value %>'" >
            <%= page_form.hidden_field :template_id, :class=>"template_id", :value=>"{{templateValueID}}", "ng-init"=>"templateValueID='" + @params_template_id.to_s + "'" %>
            <div class="btn-group mb10">
                <a href="javascript:void(0)" class="btn btn-cat btn-large w155 fsize14">{{templateValue}}</a>
                <button data-toggle="dropdown" class="btn btn-large dropdown-toggle">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu category-menu">
                    <% @templates.each do |template| %>
                    <li>
                        <a href="" ng-click="selectTemplate('<%= template.name %>','<%= template.id %>')"><%= template.name %></a>
                    </li>
                    <% end %>
                </ul>
            </div>
        </div>
	</div>
</div>
<span class="input_label">Page Content</span>
<%= cktext_area_tag("page[content]", @params_page_content, :height => 400, :uiColor => "#E3E3E3") %>
<h2><i class="icon-search"></i> SEO Settings</h2>

<%= fields_for :meta do |page_form_meta| %>
<span class="input_label">Page Header Title</span>
<%= page_form_meta.text_field :page_title, :class=>"input-block-level", :value=>@params_page_title %>
<span class="input_label">Page Description</span>
<div class="fix-textarea-width">
	<%= page_form_meta.text_area :page_description, :class=>"fullwidth", :value=>@params_page_description %>
</div>
<span class="input_label">Page Keywords (Separated by comma)</span>
<div class="fix-textarea-width">
	<%= page_form_meta.text_area :page_keywords, :class=>"fullwidth", :value=>@params_page_keywords %>
</div>
<label class="checkbox inline"> 
	<% if @params_page_no_follow %>
	<%= page_form_meta.check_box :no_follow, :checked => true %>
	<% else %>
	<%= page_form_meta.check_box :no_follow %>
	<% end %>
	<%= label_tag("meta_no_follow", "Robots Meta NOFOLLOW") %> </label>
<label class="checkbox inline"> 
	<% if @params_page_no_index %>
	<%= page_form_meta.check_box :no_index, :checked => true %>
	<% else %>
	<%= page_form_meta.check_box :no_index %>
	<% end %>
	<%= label_tag("meta_no_index", "Robots Meta NOINDEX") %> </label>
<% end %>

<div class="btn-holder">
	<a href="<%= admin_page_path %>" class="btn btn-large pull-right">Cancel</a>
	<%= submit_tag("Save",:class=>"btn btn-primary btn-large pull-right mr5") %>
	<div class="clear"></div>
</div>
<% end %>

app/views/admin/pages/edit.html.erb
<div class="btn-group">
    <a href="<%= admin_page_path %>" class="btn"><i class="icon-file"></i> Back to Pages</a>
</div>
<div class="row-fluid">
    <div class="span4">
        <% if @my_permissions.include?("can_modify_pages") %>
        <h1>Edit Page</h1>
        <% else %>
        <h1>Page Details</h1>    
        <% end %>
    </div>
    <div class="span8">
        <% if @my_permissions.include?("can_modify_pages") %>
        <div class="pull-right">
            <div class="btn-holder margin0">
                <a href="<%= admin_page_path %>" class="btn btn-large pull-right">Cancel</a>
                <a href="javascript:void(0)" class="btn btn-primary btn-large mr5 pull-right" onclick="edit_page.submit();">Update</a>
            </div>
        </div>
        <% end %>
    </div>
</div>
<% if flash[:error] %>
<div class="alert alert-error">
    <% flash[:error].each do |error_message| %>
    <%= error_message %>
    <br />
    <% end %>
</div>
<% end %>

<% if flash[:notice] %>
<div class="alert alert-success mt15">
    <button type="button" class="close" data-dismiss="alert">
        x
    </button>
    <%= flash[:notice].html_safe %>
</div>
<% end %>
<% disabled_status = !@my_permissions.include?("can_modify_pages") %>
<%= form_for :page, url: admin_update_page_path, :html => {:name => 'edit_page'} do |page_form| %>
<span class="input_label">Content Title</span>
<%= page_form.text_field :content_title, :class=>"input-block-level", "ng-model"=>"pageTitle", "ng-change"=>"populateSlug()", "ng-init"=>"pageTitle='"+@page.content_title+"'", "ng-disabled"=>disabled_status %>
<span class="input_label">Page URL</span>
<div class="row-fluid">
<div class="span10">
<%= page_form.text_field :content_title, :class=>"input-block-level", :value=> root_url + @page.url + '{{pageSlug}}', :disabled=>'disabled' %>
</div>  
<div class="span2">
<a href="<%= root_url + @page.url + @page.url_slug %>" target="_blank" class="btn pull-right pad1015">View actual page</a>
</div>
</div>
<div class="container-fluid nopadding">
    <div class="row-fluid">
        <div class="span4">
            <span class="input_label">URL Slug</span>
            <%= page_form.text_field :url_slug, :class=>"input-block-level", "ng-model"=>"pageSlug", "ng-init"=>"pageSlug='"+@page.url_slug+"'", "ng-disabled"=>disabled_status %>
        </div>
        <div class="span3">
            <span class="input_label">Page Category</span>
            <%= page_form.hidden_field :category_id, :class=>"category_id", :value=>"{{categoryValue}}", "ng-init"=>"categoryValue='"+@page_cat_name+"'" %>
            <div class="btn-group mb10">
                <a href="javascript:void(0)" class="btn btn-cat btn-large w155 fsize14" ng-disabled="<%= disabled_status %>">{{categoryValue}}</a>
                <button data-toggle="dropdown" class="btn btn-large dropdown-toggle" ng-disabled="<%= disabled_status %>">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu category-menu">
                    <% @categories.each do |category| %>
                    <li>
                        <a href="" ng-click="selectCategory('<%= category.name %>')"><%= category.name %></a>
                    </li>
                    <% end %>
                    <li class="divider"></li>
                    <li>
                        <a href="#" ng-click="selectCategory('<%= 'No Category' %>')">No Category</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="span2">
            <span class="input_label">Page Status</span>
            <%= page_form.hidden_field :status, :class=>"status", :value=>"{{statusValue.toLowerCase()}}", "ng-init"=>"statusValue='"+@page.status+"'" %>
            <div class="btn-group mb10">
                <a href="javascript:void(0)" class="btn btn-stat btn-large w75 fsize14" ng-disabled="<%= disabled_status %>" style="text-transform: capitalize">{{statusValue}}</a>
                <button data-toggle="dropdown" class="btn btn-large dropdown-toggle" ng-disabled="<%= disabled_status %>">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu status-menu">
                    <li>
                        <a href="" ng-click="selectStatus('Active')">Active</a>
                    </li>
                    <li>
                        <a href="" ng-click="selectStatus('Inactive')">Inactive</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="span3">
            <span class="input_label">Page Template</span>
            <%= page_form.hidden_field :template_id, :class=>"category_id", :value=>"{{templateValueID}}", "ng-init"=>"templateValueID='"+@page.template.id.to_s+"'" %>
            <div class="btn-group mb10">
                <a href="javascript:void(0)" class="btn btn-cat btn-large w155 fsize14" ng-init="templateValue='<%= @page.template.name %>'" ng-disabled="<%= disabled_status %>">{{templateValue}}</a>
                <button data-toggle="dropdown" class="btn btn-large dropdown-toggle" ng-disabled="<%= disabled_status %>">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu category-menu">
                    <% @templates.each do |template| %>
                    <li>
                        <a href="" ng-click="selectTemplate('<%= template.name %>','<%= template.id %>')"><%= template.name %></a>
                    </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>
<span class="input_label">Page Content</span>
<%= cktext_area_tag("page[content]", @page.content, :height => 400, :uiColor => "#E3E3E3") %>
<h2><i class="icon-search"></i> SEO Settings</h2>

<%= fields_for :meta do |page_form_meta| %>
<span class="input_label">Page Header Title</span>
<%= page_form_meta.text_field :page_title, :value=>@page.meta.page_title, :class=>"input-block-level", "ng-disabled"=>disabled_status %>
<span class="input_label">Page Description</span>
<div class="fix-textarea-width">
    <%= page_form_meta.text_area :page_description, :value=>@page.meta.page_description, :class=>"fullwidth", "ng-disabled"=>disabled_status %>
</div>
<span class="input_label">Page Keywords (Separated by comma)</span>
<div class="fix-textarea-width">
    <%= page_form_meta.text_area :page_keywords, :value=>@page.meta.page_keywords, :class=>"fullwidth", "ng-disabled"=>disabled_status %>
</div>
<label class="checkbox inline"> <%= page_form_meta.check_box :no_follow, :checked => @page.meta.no_follow, "ng-disabled"=>disabled_status %>
    <%= label_tag("meta_no_follow", "Robots Meta NOFOLLOW") %> </label>
<label class="checkbox inline"> <%= page_form_meta.check_box :no_index, :checked => @page.meta.no_index, "ng-disabled"=>disabled_status  %>
    <%= label_tag("meta_no_index", "Robots Meta NOINDEX") %> </label>
<% end %>
<% if @my_permissions.include?("can_modify_pages") %>
<div class="btn-holder">
    <a href="<%= admin_page_path %>" class="btn btn-large pull-right">Cancel</a>
    <%= submit_tag("Update",:class=>"btn btn-primary btn-large pull-right mr5") %>
    <div class="clear"></div>
</div>
<% end %>
<% end %>

app/views/admin/pages/index.html.erb
<% if @my_permissions.include?("can_modify_pages") %>
<div class="btn-group">
    <a id="add-page" class="btn" data-no-turbolink="true" href="<%= admin_add_page_path %>"><i class="icon-plus"></i> Create Page</a>
    <%= link_to raw('<i class="icon-remove"></i> Delete Page(s)'), "javascript:void(0)", id: "delete-pages", class: "btn", "ng-click"=>"deleteSelected('#delete_pages')", "ng-disabled" => "deleteButton" %>
</div>
<% end %>

<% if flash[:notice] %>
<div class="alert alert-success mt15">
    <button type="button" class="close" data-dismiss="alert">
        x
    </button>
    <%= flash[:notice].html_safe %>
</div>
<% end %>

<div class="row-fluid">
    <div class="span4">
        <h1><%= params["controller"].capitalize %></h1>
    </div>
    <div class="span8 ">
        <div class="pull-right">
            <div class="input-append">
                <form name="search_page" method="GET" action="<%= admin_page_path %>">
                    <input name="search_title" class="span9" id="appendedInputButton" type="text" placeholder="Enter Page Title" value="<%= @search_keyword %>">
                    <button class="btn h40" type="submit">
                        Search
                    </button>
                </form>
            </div>
        </div>
    </div>
    <% if @search_keyword %>
    <div class="mb20">Search Result for <strong>"<%= @search_keyword %>"</strong></div>    <% end %>
</div>
<div class="mb20">
    <div class="btn-group">
        <button class="btn">
            <%= @cat_filter_value %>
        </button>
        <button data-toggle="dropdown" class="btn dropdown-toggle">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <% @categories.each do |category| %>
            <li>
                <%= link_to category.name, :category => category.id, :creator => params[:creator], :status => params[:status] %>
            </li>
            <% end %>
            <li class="divider"></li>
            <li>
                <%= link_to "All Category", :category => "all", :creator => params[:creator], :status => params[:status] %>
            </li>
        </ul>
    </div>

    <div class="btn-group">
        <button class="btn">
            <%= @stat_filter_value %>
        </button>
        <button data-toggle="dropdown" class="btn dropdown-toggle">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li>
                <%= link_to "Active", :category => params[:category], :creator => params[:creator], :status => "active" %>
            </li>
            <li>
                <%= link_to "Inactive", :category => params[:category], :creator => params[:creator], :status => "inactive"  %>
            </li>
            <li class="divider"></li>
            <li>
                <%= link_to "All Status", :status => "all", :creator => params[:creator], :category => params[:category] %>
            </li>
        </ul>
    </div>

    <div class="btn-group hidden-phone">
        <button class="btn">
            <%= @creator_filter_value %>
        </button>
        <button data-toggle="dropdown" class="btn dropdown-toggle">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <% @creators.each do |creator| %>
            <li>
                <%= link_to creator.fullname, :creator => creator.id, :status => params[:status], :category => params[:category] %>
            </li>
            <% end %>
            <li class="divider"></li>
            <li>
                <%= link_to "All Creator", :creator => "all", :status => params[:status], :category => params[:category] %>
            </li>
        </ul>
    </div>
</div>
<% unless @pages.empty?  %>
<% delete_confirm = 'return confirm("Are you sure you want to delete the selected page? \nNote: There\'s no undo.");return false;' %>
<%= form_tag(admin_delete_page_path, :id => 'delete_pages', method: "POST", :onsubmit => delete_confirm ) do %>
<table class="table table-striped">
    <thead>
        <tr>
            <% if @my_permissions.include?("can_modify_pages") %>
            <th><%= check_box_tag "page_all", "all", false, :id => "page_all", "ng-model" => "masters", "ng-checked"=>"masterSelect", "ng-click"=>"selectAll(masters," + @pages.count.to_s + ")"  %></th>
            <% end %>
            <th>ID</th>
            <th>Title</th>
            <th>Created By</th>
            <th>Category</th>
            <th>Status</th>
            <th class="hidden-phone">Last Modified</th>
        </tr>
    </thead>
    <tbody>
        <% @pages.each do |page| %>
        <tr>
            <% if @my_permissions.include?("can_modify_pages") %>
            <td><%= check_box_tag "page_ids[]", page.id, false, :class => 'checkbox_item', :id => "user_#{page.id}", "ng-model"=>"page"+page.id.to_s, "ng-checked" => "masters","ng-click"=>"selectItem(page"+page.id.to_s+")" %></td>
            <% end %>
            <td><%= page.id %></td>
            <% age_name_dots = (page.content_title.length >= 55 )? "..." : "" %>
            <td><%= link_to page.content_title[0,55] + age_name_dots, admin_edit_page_path(@admin_slug, page.id), 'data-no-turbolink' => true, 'title' => page.content_title  %></td>
            <% if page.user.present? %>
            <td><%= page.user.fullname %></td>
            <% else %>
            <td>Unknown</td>
            <% end %>
            <% if page.category.present? %>
            <td><%= page.category.name %></td>
            <% else %>
            <td></td>
            <% end %>
            <% if page.status == "active" %>
            <td><span class="label label-success"><%= page.status %></span></td>
            <% else %>
            <td><span class="label"><%= page.status %></span></td>
            <% end %>
            <td class="hidden-phone"><%= page.modified %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<% end %>
<div class="pull-right">
    <%= paginate @pages %>
</div>
<div style="clear:both"></div>
<% else %>
<% if @record_count > 0  %>
<p>
    No results were found for your request! <a href="<%= admin_page_path %>">Back to Pages.</a>
</p>
<% else %>
<p>
    No Pages found. <a href="<%= admin_add_page_path %>">create now?</a>
</p>
<% end %>
<% end %>