config/routes.rb
Fusionpanel::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'main#index'

	post 'sendmessage' => 'frontpage#sendmessage', as: 'sendmessage'
	
  get 'adduser' => 'admin#add_user', as: :add_user
  post 'adduser' => 'admin#create_user', as: :create_user

  get ':mainslug' => 'main#router', as: 'admin'
  get ':mainslug/visitorinfo/:filter_type' => 'main#visitor_info', as: 'admin_visitor_info'
  get ':mainslug/login' => 'main#router', as: 'admin_index'
  post ':mainslug/login' => 'admin#login_connect', as: 'login_connect'
  get ':mainslug/logout' => 'admin#logout', as: 'admin_logout'
	get ':mainslug/resetpassword' => 'main#resetpassword', as: 'admin_resetpassword_user'
	post ':mainslug/resetpassword' => 'main#resetpassword_submit', as: 'admin_resetpassword_submit_user'
	
  get ':mainslug/pages' => 'pages#index', as: 'admin_page'
  get ':mainslug/pages/add' => 'pages#add', as: 'admin_add_page'
  post ':mainslug/pages/add' => 'pages#create', as: 'admin_create_page'
  get ':mainslug/pages/edit/:id' => 'pages#edit', as: 'admin_edit_page'
  post ':mainslug/pages/edit/:id' => 'pages#update', as: 'admin_update_page'
  post ':mainslug/pages/delete' => 'pages#delete', as: 'admin_delete_page'

  get ':mainslug/categories' => 'categories#index', as: 'admin_category'
  post ':mainslug/categories/add' => 'categories#create', as: 'admin_create_category'
  post ':mainslug/categories/delete' => 'categories#delete', as: 'admin_delete_category'
  get ':mainslug/categories/edit/:id' => 'categories#edit', as: 'admin_edit_category'
  post ':mainslug/categories/edit/:id' => 'categories#update', as: 'admin_update_category'

  get ':mainslug/users' => 'users#index', as: 'admin_user'
  post ':mainslug/users/add' => 'users#add', as: 'admin_add_user'
  get ':mainslug/create-account/:token' => 'users#create_account', as: 'admin_createaccount_user'
  get ':mainslug/users/role' => 'users#role_index', as: 'admin_user_role'
  get ':mainslug/users/role/add' => 'users#add_role', as: 'admin_user_addrole'
  post ':mainslug/users/role/add' => 'users#create_role', as: 'admin_user_createrole'
  get ':mainslug/users/role/edit/:id' => 'users#edit_role', as: 'admin_user_editrole'
  post ':mainslug/users/role/edit/:id' => 'users#update_role', as: 'admin_user_updatetrole'
  post ':mainslug/users/role/delete' => 'users#delete_role', as: 'admin_delete_role'
  get ':mainslug/users/:username' => 'users#profile', as: 'admin_user_profile'
  post ':mainslug/create-account/:token' => 'users#create', as: 'admin_create_user'
  post ':mainslug/users/changerole' => 'users#changerole', as: 'admin_changerole_user'
  post ':mainslug/users/delete' => 'users#delete', as: 'admin_delete_user'
  post ':mainslug/users/changepassword' => 'users#changepassword', as: 'admin_changepassword_user'
  post ':mainslug/users/forgotpassword' => 'main#forgotpassword', as: 'admin_forgotpassword_user'
  
  get ':mainslug/widgets' => 'widgets#index', as: 'admin_widget'
  get ':mainslug/widgets/add' => 'widgets#add', as: 'admin_add_widget'
  post ':mainslug/widgets/add' => 'widgets#create', as: 'admin_create_widget'
  post ':mainslug/widgets/delete' => 'widgets#delete', as: 'admin_delete_widget'
  get ':mainslug/widgets/edit/:id' => 'widgets#edit', as: 'admin_edit_widget'
  post ':mainslug/widgets/edit/:id' => 'widgets#update', as: 'admin_update_widget'

  get ':mainslug/assets' => 'assets#index', as: 'admin_asset'
  get ':mainslug/file_writer/:file_id' => 'assets#file_writer', as: 'admin_asset_filewriter'
  get ':mainslug/template_loader' => 'assets#template_loader', as: 'admin_asset_templateloader'
  post ':mainslug/assets/upload' => 'assets#upload', as: 'admin_assets_upload'
  post ':mainslug/assets/create_dir' => 'assets#create_dir', as: 'admin_assets_create_dir'
  get ':mainslug/assets/edit/:file_id' => 'assets#edit_file', as: 'admin_asset_edit_file'
  post ':mainslug/assets/edit/:file_id' => 'assets#update_file', as: 'admin_asset_update_file'
  get ':mainslug/assets/download/:file_id' => 'assets#download', as: 'admin_asset_download'
  post ':mainslug/assets/delete' => 'assets#delete', as: 'admin_asset_delete'

  get ':mainslug/settings' => 'settings#index', as: 'admin_setting'
  post ':mainslug/settings/update' => 'settings#update', as: 'admin_setting_update'
  post ':mainslug/settings/updatepage' => 'settings#updatepage', as: 'admin_setting_updatepage'
  post ':mainslug/settings/updatesmtp' => 'settings#update_smtp', as: 'admin_setting_updatesmtp'
  
  get ':mainslug/templates' => 'templates#index', as: 'admin_template'
  get ':mainslug/templates/add' => 'templates#add', as: 'admin_add_template'
  post ':mainslug/templates/create' => 'templates#create', as: 'admin_create_template'
  post ':mainslug/templates/delete' => 'templates#delete', as: 'admin_delete_template'
  get ':mainslug/templates/edit/:id' => 'templates#edit', as: 'admin_edit_template'
  post ':mainslug/templates/edit/:id' => 'templates#update', as: 'admin_update_template'

  get ':mainslug/webtraffic' => 'webtraffic#index', as: 'admin_webtraffic'
  get ':mainslug/webtraffic/:id' => 'webtraffic#details', as: 'admin_webtraffic_details'
  
  get ':mainslug/adminactivities' => 'adminactivities#index', as: 'admin_adminactivities'
  
  get ':mainslug/about' => 'about#index', as: 'admin_about'
  
  get '*pagecats/:page' => 'frontpage#index', as: 'frontendpage'
  

end

app/views/layouts/fusionpanel/fusionpanel.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= render "layouts/fusionpanel/partial/header" %>
</head>
<body ng-app="fusionpanel">
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="<%= admin_path %>" class="brand"><%=image_tag("fusionpanel_small.png", alt: "Fusionpanel", width: 136)%> - <%= session[:admin_title] %></a>
			<a style="color:#ffffff" target="_blank" href="<%= root_url %>" class="brand">View actual site <%=image_tag("eye_icon.png", alt: "View site", width: 22)%></a>
			<div class="nav-collapse collapse">
				<p class="navbar-text pull-right">
					<img src="http://www.gravatar.com/avatar/<%= session[:gravatar_hash] %>?s=28" class="mr5"> 
					<a class="navbar-link" href="<%= root_url + session[:admin_slug] + "/users/" + session[:username] %>"><%= session[:fullname] %></a> (<%= session[:role] %>) |
					<a class="navbar-link" href="<%= admin_logout_path %>">Logout</a>
				</p>
			</div>
		</div>
	</div>
</div>
<% set_active_nav = Hash[params["controller"] => ' class="active"'] %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span2">
			<div class="well sidebar-nav">
				<ul class="nav nav-list">
					<li class="nav-header">Website</li>
					<li<%= raw set_active_nav["admin"] %>><a href="<%= admin_path %>"><i class="icon-home"></i> Dashboard</a></li>
					<% if @my_permissions.include?("can_view_pages") %>
					<li<%= raw set_active_nav["pages"] %>><a href="<%= admin_page_path %>"><i class="icon-file"></i> Pages</a></li>
					<% end %>
					<% if @my_permissions.include?("can_view_categories") %>
					<li<%= raw set_active_nav["categories"] %>><a href="<%= admin_category_path %>"><i class="icon-th-list"></i> Categories</a></li>
					<% end %>
					<% if @my_permissions.include?("can_view_widgets") %>
					<li<%= raw set_active_nav["widgets"] %>><a href="<%= admin_widget_path %>"><i class="icon-move"></i> Widgets</a></li>
					<% end %>
					<% if @my_permissions.include?("can_view_assets") %>
					<li<%= raw set_active_nav["assets"] %>><a href="<%= admin_asset_path %>"><i class="icon-picture"></i> Assets</a></li>
					<% end %>
					<% if @my_permissions.include?("can_view_users") %>
					<li<%= raw set_active_nav["users"] %>><a href="<%= admin_user_path %>"><i class="icon-user"></i> Users</a></li>
					<% end %>
					<% if (@my_permissions & ["can_view_settings", "can_view_templates"]).present? %>
					<li class="nav-header">Configuration</li>
					<% end %>
					<% if @my_permissions.include?("can_view_settings") %>
					<li<%= raw set_active_nav["settings"] %>><a href="<%= admin_setting_path %>"><i class="icon-wrench"></i> Settings</a></li>
					<% end %>
					<% if @my_permissions.include?("can_view_templates") %>
					<li<%= raw set_active_nav["templates"] %>><a href="<%= admin_template_path %>"><i class="icon-th-large"></i> Templates</a></li>
					<% end %>
					<li class="nav-header">Logs</li>
                    <li<%= raw set_active_nav["webtraffic"] %>><a href="<%= admin_webtraffic_path %>"><i class="icon-eye-open"></i> Web Traffic</a></li>
                    <li<%= raw set_active_nav["adminactivities"] %>><a href="<%= admin_adminactivities_path %>"><i class="icon-lock"></i> Admin Activities</a></li>
					<li class="nav-header">Info</li>
					<li<%= raw set_active_nav["about"] %>><a href="<%= admin_about_path %>"><i class="icon-info-sign"></i> About</a></li>
				</ul>
			</div>
		</div>
		<div class="span10">
			<div class="main-content" ng-controller="<%= params[:controller] %>">
			    
				<%= yield %>			
			</div>
		</div>
	</div>
</div>
<% if params[:controller] == "settings"  %>
<script>
  var editor404page = CodeMirror.fromTextArea(document.getElementById("page404content"), {
    lineNumbers: true,
    mode: "application/x-ejs",
    indentWithTabs: true,
   
  });
  var editorOfflinepage = CodeMirror.fromTextArea(document.getElementById("pageOfflinecontent"), {
    lineNumbers: true,
    mode: "application/x-ejs",
    indentWithTabs: true,
   
  });
   $('#404PageModal').on('shown', function() { editor404page.refresh() })
   $('#offlinePageModal').on('shown', function() { editorOfflinepage.refresh() })
</script>
<% end %>
<% if params[:controller] == "templates"  %>
<script>
  var templateEditor = CodeMirror.fromTextArea(document.getElementById("pageTemplatecontent"), {
    lineNumbers: true,
    mode: "application/x-ejs",
    indentWithTabs: true,
  });
</script>
<% end %>
<script data-turbolinks-track="true" src="/assets/angular.min.js?body=1"></script>
<% if params[:controller] == "assets"  %>
<script data-turbolinks-track="true" src="/assets/bootstrap-filestyle.min.js?body=1"></script>
<%= javascript_tag do %>
        $(document).ready(function() {
            $('.fancybox').fancybox();
        });
<% end %>
<script>
  var editorPage = CodeMirror.fromTextArea(document.getElementById("fileContent"), {
    lineNumbers: true,
    mode: "<%= @asset_file_type %>",
    indentWithTabs: true,
   
  });
   $('#fileContent').on('shown', function() { editorPage.refresh() })
</script>
<% end %>
<%= javascript_include_tag params[:controller] %>
</body>
</html>

app/views/layouts/fusionpanel/plain.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Fusionpanel</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= stylesheet_link_tag "admin",params[:controller], "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
		<%= javascript_tag do %>
		window.appController = "<%= params[:controller] %>";
		window.authenticityToken = "<%= form_authenticity_token %>";
		window.baseURL = "<%= root_url %>";
		window.adminSlug = "<%= @admin_slug %>";
		<% end %>
	</head>
	<body ng-app="fusionpanel">

		<%= yield %>

		<footer class="footer text-center fsize12">
			Fusionpanel v 1.0.6
		</footer>
		<script data-turbolinks-track="true" src="/assets/angular.min.js?body=1"></script>
		<%= javascript_include_tag params[:controller] %>
	</body>
</html>

app/views/layouts/fusionpanel/userlogin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Fusionpanel</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= stylesheet_link_tag params[:controller], "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= javascript_include_tag params[:controller], "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<%= yield %>

	</body>
</html>