config/routes.rb
Fusionpanel::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'main#index'

	post 'sendmessage' => 'frontpage#sendmessage', as: 'sendmessage'
	
  get 'adduser' => 'admin#add_user', as: :add_user
  post 'adduser' => 'admin#create_user', as: :create_user

  get ':mainslug' => 'main#router', as: 'admin'
  get ':mainslug/visitorinfo/:filter_type' => 'main#visitor_info', as: 'admin_visitor_info'
  get ':mainslug/login' => 'main#router', as: 'admin_index'
  post ':mainslug/login' => 'admin#login_connect', as: 'login_connect'
  get ':mainslug/logout' => 'admin#logout', as: 'admin_logout'
	get ':mainslug/resetpassword' => 'main#resetpassword', as: 'admin_resetpassword_user'
	post ':mainslug/resetpassword' => 'main#resetpassword_submit', as: 'admin_resetpassword_submit_user'
	
  get ':mainslug/pages' => 'pages#index', as: 'admin_page'
  get ':mainslug/pages/add' => 'pages#add', as: 'admin_add_page'
  post ':mainslug/pages/add' => 'pages#create', as: 'admin_create_page'
  get ':mainslug/pages/edit/:id' => 'pages#edit', as: 'admin_edit_page'
  post ':mainslug/pages/edit/:id' => 'pages#update', as: 'admin_update_page'
  post ':mainslug/pages/delete' => 'pages#delete', as: 'admin_delete_page'

  get ':mainslug/categories' => 'categories#index', as: 'admin_category'
  post ':mainslug/categories/add' => 'categories#create', as: 'admin_create_category'
  post ':mainslug/categories/delete' => 'categories#delete', as: 'admin_delete_category'
  get ':mainslug/categories/edit/:id' => 'categories#edit', as: 'admin_edit_category'
  post ':mainslug/categories/edit/:id' => 'categories#update', as: 'admin_update_category'

  get ':mainslug/users' => 'users#index', as: 'admin_user'
  post ':mainslug/users/add' => 'users#add', as: 'admin_add_user'
  get ':mainslug/create-account/:token' => 'users#create_account', as: 'admin_createaccount_user'
  get ':mainslug/users/role' => 'users#role_index', as: 'admin_user_role'
  get ':mainslug/users/role/add' => 'users#add_role', as: 'admin_user_addrole'
  post ':mainslug/users/role/add' => 'users#create_role', as: 'admin_user_createrole'
  get ':mainslug/users/role/edit/:id' => 'users#edit_role', as: 'admin_user_editrole'
  post ':mainslug/users/role/edit/:id' => 'users#update_role', as: 'admin_user_updatetrole'
  post ':mainslug/users/role/delete' => 'users#delete_role', as: 'admin_delete_role'
  get ':mainslug/users/:username' => 'users#profile', as: 'admin_user_profile'
  post ':mainslug/create-account/:token' => 'users#create', as: 'admin_create_user'
  post ':mainslug/users/changerole' => 'users#changerole', as: 'admin_changerole_user'
  post ':mainslug/users/delete' => 'users#delete', as: 'admin_delete_user'
  post ':mainslug/users/changepassword' => 'users#changepassword', as: 'admin_changepassword_user'
  post ':mainslug/users/forgotpassword' => 'main#forgotpassword', as: 'admin_forgotpassword_user'
  
  get ':mainslug/widgets' => 'widgets#index', as: 'admin_widget'
  get ':mainslug/widgets/add' => 'widgets#add', as: 'admin_add_widget'
  post ':mainslug/widgets/add' => 'widgets#create', as: 'admin_create_widget'
  post ':mainslug/widgets/delete' => 'widgets#delete', as: 'admin_delete_widget'
  get ':mainslug/widgets/edit/:id' => 'widgets#edit', as: 'admin_edit_widget'
  post ':mainslug/widgets/edit/:id' => 'widgets#update', as: 'admin_update_widget'

  get ':mainslug/assets' => 'assets#index', as: 'admin_asset'
  get ':mainslug/file_writer/:file_id' => 'assets#file_writer', as: 'admin_asset_filewriter'
  get ':mainslug/template_loader' => 'assets#template_loader', as: 'admin_asset_templateloader'
  post ':mainslug/assets/upload' => 'assets#upload', as: 'admin_assets_upload'
  post ':mainslug/assets/create_dir' => 'assets#create_dir', as: 'admin_assets_create_dir'
  get ':mainslug/assets/edit/:file_id' => 'assets#edit_file', as: 'admin_asset_edit_file'
  post ':mainslug/assets/edit/:file_id' => 'assets#update_file', as: 'admin_asset_update_file'
  get ':mainslug/assets/download/:file_id' => 'assets#download', as: 'admin_asset_download'
  post ':mainslug/assets/delete' => 'assets#delete', as: 'admin_asset_delete'

  get ':mainslug/settings' => 'settings#index', as: 'admin_setting'
  post ':mainslug/settings/update' => 'settings#update', as: 'admin_setting_update'
  post ':mainslug/settings/updatepage' => 'settings#updatepage', as: 'admin_setting_updatepage'
  post ':mainslug/settings/updatesmtp' => 'settings#update_smtp', as: 'admin_setting_updatesmtp'
  
  get ':mainslug/templates' => 'templates#index', as: 'admin_template'
  get ':mainslug/templates/add' => 'templates#add', as: 'admin_add_template'
  post ':mainslug/templates/create' => 'templates#create', as: 'admin_create_template'
  post ':mainslug/templates/delete' => 'templates#delete', as: 'admin_delete_template'
  get ':mainslug/templates/edit/:id' => 'templates#edit', as: 'admin_edit_template'
  post ':mainslug/templates/edit/:id' => 'templates#update', as: 'admin_update_template'

  get ':mainslug/webtraffic' => 'webtraffic#index', as: 'admin_webtraffic'
  get ':mainslug/webtraffic/:id' => 'webtraffic#details', as: 'admin_webtraffic_details'
  
  get ':mainslug/adminactivities' => 'adminactivities#index', as: 'admin_adminactivities'
  
  get ':mainslug/about' => 'about#index', as: 'admin_about'
  
  get '*pagecats/:page' => 'frontpage#index', as: 'frontendpage'
  

end

app/models/setting.rb
class Setting < ActiveRecord::Base
    validates :setting_name, presence: true, uniqueness: true
    SMTP_URL = 'Setting.find(1).setting_name'
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  layout :set_layout
  before_action :require_login, :check_admin_slug
  
  def index
    @my_permissions = my_permissions
    @admin_slug = admin_backend_slug
    if my_permissions.include?("can_view_settings")
      page404_line_code = ""
      pageOffline_line_code = ""
      
      File.open("public/404.html", "r") do |f|
        f.each_line do |line|
          page404_line_code += line
        end
      end
      
      File.open("public/offline.html", "r") do |f2|
        f2.each_line do |line2|
          pageOffline_line_code += line2
        end
      end
      
      @page404_content =  page404_line_code.html_safe
      @pageOffline_content =  pageOffline_line_code.html_safe
      @pages = Page.all
  
      #load admin settings
      admin_settings = Hash.new
      admin_settings["admin_slug"] = Setting.find_by_setting_name('admin_slug').setting_value
      admin_settings["web_status"] = Setting.find_by_setting_name('web_status').setting_value
      admin_settings["company_name"] = Setting.find_by_setting_name('company_name').setting_value
      admin_settings["admin_title"] = Setting.find_by_setting_name('admin_title').setting_value
      admin_settings["generic_meta_description"] = Setting.find_by_setting_name('generic_meta_description').setting_value
      admin_settings["generic_meta_keywords"] = Setting.find_by_setting_name('generic_meta_keywords').setting_value
      
      admin_settings["smtp_address"] = Setting.find_by_setting_name('smtp_address').setting_value
      admin_settings["smtp_port"] = Setting.find_by_setting_name('smtp_port').setting_value
      admin_settings["smtp_domain"] = Setting.find_by_setting_name('smtp_domain').setting_value
      admin_settings["smtp_username"] = Setting.find_by_setting_name('smtp_username').setting_value
      admin_settings["smtp_password"] = Setting.find_by_setting_name('smtp_password').setting_value
      admin_settings["admin_email"] = Setting.find_by_setting_name('admin_email').setting_value
      
      homepage_setting_value = Setting.find_by_setting_name('homepage').setting_value
      admin_settings["homepage_id"] = !homepage_setting_value.empty? ? homepage_setting_value : nil
      
      if !page_exist? homepage_setting_value
      	admin_settings["homepage_id"] = nil
      end
      
      homepage_value = !admin_settings["homepage_id"].nil? ? Page.find(admin_settings["homepage_id"]).content_title : 'Please select page'
      admin_settings["homepage_value"] = homepage_value.length >= 25 ? homepage_value[0,25] + '...' : homepage_value
      @admin_settings = admin_settings
      session[:admin_title] = Setting.find_by_setting_name('admin_title').setting_value
      @ips = block_ips
      render 'admin/settings/index'
    else
      render 'admin/restricted'
    end
  end

  def update
    @my_permissions = my_permissions
    if my_permissions.include?("can_modify_settings")
      setting = {
        1 => { "setting_value" => params[:admin_slug] },
        2 => { "setting_value" => params[:web_status] },
        3 => { "setting_value" => params[:company_name] },
        4 => { "setting_value" => params[:admin_title] },
        5 => { "setting_value" => params[:homepage] },
        6 => { "setting_value" => params[:generic_meta_description] },
        7 => { "setting_value" => params[:generic_meta_keywords] },
        13 => { "setting_value" => params[:admin_email] },
      }
  
      additional_block_ip = params[:block_ips].split("\r\n") - block_ips
      deleted_block_ip = block_ips - params[:block_ips].split("\r\n")
  
      # Add block IP
  
      additional_block_ip.each do |new_ip|
        if new_ip != ""
          BlockIp.create(:ip => new_ip)
        end
      end
  
      # Remove block IP
  
      deleted_block_ip.each do |new_ip|
        BlockIp.where(:ip => new_ip).destroy_all
      end
  
      if Setting.update(setting.keys, setting.values)
        flash[:notice] = "Settings successfully updated!"
        session[:admin_slug] = params[:admin_slug]
        log_user_activities 'update_setting', 'updated <strong>Settings</strong>'
        redirect_to root_url + session[:admin_slug] + "/settings" #admin_setting_path
      else
        flash[:notice] = "<strong>Error Updating!</strong>"
        redirect_to admin_setting_path
      end
    else
      render 'admin/restricted'
    end

  end

  def updatepage
    @my_permissions = my_permissions
    page_type = params[:pagetype]
    if my_permissions.include?("can_modify_settings")
      if page_type == 'page404'
        page_document = '404.html'
      else
        page_document = 'offline.html'
      end
      
      page_content = params[:content]
      
      begin
        File.open('public/' + page_document, 'w') do |f2|
          f2.puts page_content
        end
        if page_type == 'page404'
          log_user_activities 'update_setting', 'updated <strong>404 page setting</strong>'
        else
          log_user_activities 'update_setting', 'updated <strong>Offline page setting</strong>'
        end
        flash[:notice] = page_document.capitalize + " page is successfully updated"
        redirect_to admin_setting_path
      rescue
        flash[:notice] = "Error saving page. Please try again later."
        redirect_to admin_setting_path
      end
    else
      render 'admin/restricted'
    end
  end

  def update_smtp
    @my_permissions = my_permissions
    if my_permissions.include?("can_modify_settings")
      response = Hash.new
      setting = {
         8 => { "setting_value" => params[:smtp_address] },
         9 => { "setting_value" => params[:smtp_port] },
        10 => { "setting_value" => params[:smtp_domain] },
        11 => { "setting_value" => params[:smtp_username] },
        12 => { "setting_value" => params[:smtp_password] },
      }
      
      if Setting.update(setting.keys, setting.values)
        flash[:notice] = "SMTP Settings successfully updated!"
        response["code"] = 100
        response["message"] = "Success"
      else
        response["code"] = 201
        response["message"] = "Error Updating SMTP. Please try again."
      end 

    else
        response["code"] = 201
        response["message"] = User::PERMISSION_ERROR_MSG
    end
    
    render json:response

  end

  def block_ips
    ips = BlockIp.all
    ips_arr = []
    ips.each do |block_ip|
      ips_arr.push(block_ip.ip)
    end
    return ips_arr
  end
end

app/views/admin/settings/index.html.erb
<script>
     CKEDITOR.config.toolbar= [
     { name: 'document',    items : [ 'Source','-','Save','NewPage','DocProps','Preview','-','Templates' ] }
  ]
</script>
<div class="row-fluid mb10">
    <div class="span4">
        <h1><%= params["controller"].capitalize %></h1>
    </div>
    <% if @my_permissions.include?("can_modify_settings") %>
    <div class="span8">
        <div class="pull-right">
            <div class="btn-holder margin0">
                <a href="javascript:void(0)" class="btn btn-primary btn-large mr5 pull-right" ng-click="updateSetting()">Update</a>
            </div>
        </div>
    </div>
    <% end %>
</div>

<% if flash[:error] %>
<div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">
        x
    </button>
    <% flash[:error].each do |error_message| %>
    <%= error_message %>
    <br />
    <% end %>
</div>
<% end %>

<% if flash[:notice] %>
<div class="alert alert-success mt15">
    <button type="button" class="close" data-dismiss="alert">
        x
    </button>
    <%= flash[:notice].html_safe %>
</div>
<% end %>

<% disabled_status = !@my_permissions.include?("can_modify_settings") %>
<%= form_tag(admin_setting_update_path, method: "post", id: "updateSetting") do %>
<div class="row-fluid">
    <div class="span6">
        <div class="row-fluid ">
            <div class="span4"><label>Admin Entry Slug</label></div>
            <div class="span8"><input type="text" name="admin_slug" class="input-block-level w400" value="<%= @admin_settings['admin_slug'] %>" ng-disabled="<%= disabled_status %>" ></div>
        </div>
        <div class="row-fluid ">
            <div class="span4"><label>Admin Email</label></div>
            <div class="span8"><input type="text" name="admin_email" class="input-block-level w400" value="<%= @admin_settings['admin_email'] %>" ng-disabled="<%= disabled_status %>" ></div>
        </div>
         <div class="row-fluid entry-slug">
            <div class="span4"><label>Homepage</label></div>
            
            <div class="span8">
            	<% if @pages.count > 0 %>
                <input type="hidden" name="homepage" value="{{HomepageValueID}}" ng-init="HomepageValueID='<%= @admin_settings['homepage_id'] %>'" />
                <div class="btn-group mb10">
                    <a href="javascript:void(0)" class="btn fsize14" ng-init="HomepageValue='<%= @admin_settings["homepage_value"] %>'" ng-disabled="<%= disabled_status %>">{{HomepageValue}}</a>
                    <button data-toggle="dropdown" class="btn dropdown-toggle" ng-disabled="<%= disabled_status %>">
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu status-menu">
                        <% @pages.each do |page| %>
                        <li>
                            <a href="" ng-click="selectHomepage('<%= page.content_title %>','<%= page.id %>')"><%= page.content_title %></a>
                        </li>
                        <% end %>
                    </ul>
                </div>
				<% else %>
					<input type="hidden" name="homepage" value="" />
					No any page to set as your homepage. <a href="<%= admin_create_page_path %>">Create Now?</a>
				<% end %>
            </div>

        </div>
        
        <div class="row-fluid">
            <div class="span4"><label>Company Name</label></div>
            <div class="span8"><input type="text" name="company_name" class="input-block-level w400"  value="<%= @admin_settings['company_name'] %>" ng-disabled="<%= disabled_status %>"></div>
        </div>

        <div class="row-fluid">
            <div class="span4"><label>Web Admin Title</label></div>
            <div class="span8"><input type="text" name="admin_title" class="input-block-level w400"  value="<%= @admin_settings['admin_title'] %>" ng-disabled="<%= disabled_status %>"></div>
        </div>

        <div class="row-fluid">
            <div class="span4"><label>Generic Meta Tag Description</label></div>
            <div class="span8"><textarea name="generic_meta_description" rows="3" class="input-block-level w400 h90" ng-disabled="<%= disabled_status %>" ><%= @admin_settings['generic_meta_description'] %></textarea></div>
        </div>
        
        <div class="row-fluid mw500">
            <div class="span4"><label>Generic Meta Tag Keywords</label></div>
            <div class="span8"><textarea name="generic_meta_keywords" rows="3" class="input-block-level w400 h90" ng-disabled="<%= disabled_status %>"><%= @admin_settings['generic_meta_keywords'] %></textarea></div>
        </div>
        
        <div class="row-fluid">
            <div class="span4"><label>SMTP Settings</label></div>
            <div class="span8"><a href="#SMTPSettings" role="button" class="btn" data-toggle="modal">Edit SMTP Settings</a></div>
        </div>
        
    </div>
    <div class="span6">
        <div class="row-fluid btnonoff mb10" ng-init="switchPresence('<%= @admin_settings['web_status'] %>')">
            <div class="btnonoff-wrap">
                <div class="span8 ">
                <input type="hidden" name="web_status" value="{{presence}}" >
                <p>Website Presence Status <span class="label capitalize" ng-class="presenceLabel">{{presence}}</span></p>
                </div>
                <div class="span4">
                    <% if @my_permissions.include?("can_modify_settings") %>
                    <a class="btn btn-small pull-right" ng-class="presenceButton" ng-click="switchPresence(toswitch)" type="button">Switch to <span class="capitalize">{{toswitch}}</span></a>
                    <% else %>
                    <a class="btn btn-small pull-right" ng-class="presenceButton" type="button" ng-disabled="<%= disabled_status %>" >Switch to <span class="capitalize">{{toswitch}}</span></a>
                    <% end %>
                </div>
            </div>
        </div>
        <p>Blocked IP lists</p>
        <%= text_area_tag(:block_ips , @ips.join("\n"), class: "input-block-level w400 h150", "ng-disabled"=>disabled_status) %>
        <div style="text-align: right">
        <a href="#offlinePageModal" role="button" class="btn" type="button"  data-toggle="modal">Edit Offline Page</a>
        <a href="#404PageModal" role="button" class="btn" type="button"  data-toggle="modal">Edit 404 Page</a>
        </div>
    </div>
</div>
<% end %>

<div id="offlinePageModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <%= form_tag(admin_setting_updatepage_path, method: "post", id: "updateSetting") do %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 id="modal-header">Offline Page Snippet</h3>
  </div>
  <div class="modal-body">
     <input type="hidden" name="pagetype" value="pageOffline" />
     <textarea id="pageOfflinecontent" name="content" class="input-block-level w400 h300" ><%= raw( @pageOffline_content ) %></textarea>
  </div>
  
  <div class="modal-footer">
    <% if @my_permissions.include?("can_modify_settings") %>
    <a id="invite-user-cancel" ng-disabled="buttonControl" class="btn btn-large link-cancel" data-dismiss="modal" aria-hidden="true">Cancel</a>
    <button ng-disabled="buttonControl" type="submit" class="btn btn-primary btn-large btn-cancel" ng-click="inviteUser('/users/add')">
            Update
    </button>
    <% end %>
  </div>
  <% end %>
</div>


<div id="404PageModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <%= form_tag(admin_setting_updatepage_path, method: "post", id: "updateSetting") do %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 id="modal-header">404 Page Snippet</h3>
  </div>
  <div class="modal-body">
      <input type="hidden" name="pagetype" value="page404" />
      <textarea id="page404content" name="content" class="input-block-level w400 h300" ><%= raw( @page404_content ) %></textarea>
  </div>
  <div class="modal-footer">
    <% if @my_permissions.include?("can_modify_settings") %>
    <a id="invite-user-cancel" ng-disabled="buttonControl" class="btn btn-large link-cancel" data-dismiss="modal" aria-hidden="true">Cancel</a>
    <button ng-disabled="buttonControl" type="submit" class="btn btn-primary btn-large btn-cancel" ng-click="inviteUser('/users/add')">
            Update
    </button>
    <% end %>
  </div>
  <% end %>
</div>
<div id="SMTPSettings" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <%= form_tag(admin_setting_updatesmtp_path, method: "post", id: "updateSetting") do %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 id="modal-header">SMTP Settings</h3>
  </div>
  <div class="modal-body">
  	<div class="message-status" ng-bind-html-unsafe="messageStatus"></div>
    <div class="row-fluid">
        <div class="span3"><label>Address</label></div>
        <div class="span9"><input type="text" name="smtp_address" ng-model="smtpAddress" class="input-block-level w400" ng-init="smtpAddress='<%= @admin_settings['smtp_address'] %>'" ng-disabled="<%= disabled_status %>"></div>
    </div>
    <div class="row-fluid">
        <div class="span3"><label>Port</label></div>
        <div class="span9"><input type="text" name="smtp_port" ng-model="smtpPort" class="input-block-level w400" ng-init="smtpPort='<%= @admin_settings['smtp_port'] %>'" ng-disabled="<%= disabled_status %>"></div>
    </div>
    <div class="row-fluid">
        <div class="span3"><label>Domain</label></div>
        <div class="span9"><input type="text" name="smtp_domain" ng-model="smtpDomain" class="input-block-level w400" ng-init="smtpDomain='<%= @admin_settings['smtp_domain'] %>'" ng-disabled="<%= disabled_status %>"></div>
    </div>
    <div class="row-fluid">
        <div class="span3"><label>Username</label></div>
        <div class="span9"><input type="text" name="smtp_username" ng-model="smtpUsername" class="input-block-level w400" ng-init="smtpUsername='<%= @admin_settings['smtp_username'] %>'" ng-disabled="<%= disabled_status %>" autocomplete="off" /></div>
    </div>
    <div class="row-fluid">
        <div class="span3"><label>Password</label></div>
        <div class="span9"><input type="password" name="smtp_password" ng-model="smtpPassword" class="input-block-level w400" ng-init="smtpPassword='<%= @admin_settings['smtp_password'] %>'" ng-disabled="<%= disabled_status %>" autocomplete="off" /></div>
    </div>
  </div>
  <div class="modal-footer">
    <% if @my_permissions.include?("can_modify_settings") %>
    <a id="update-smtp-cancel" ng-disabled="buttonControl" class="btn btn-large link-cancel" data-dismiss="modal" aria-hidden="true">Cancel</a>
    <button ng-disabled="buttonControl" type="submit" class="btn btn-primary btn-large btn-cancel" ng-click="updateSMTP('/settings/updatesmtp')">
            Update
    </button>
    <% end %>
  </div>
  <% end %>
</div>