config/routes.rb
Fusionpanel::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'main#index'

	post 'sendmessage' => 'frontpage#sendmessage', as: 'sendmessage'
	
  get 'adduser' => 'admin#add_user', as: :add_user
  post 'adduser' => 'admin#create_user', as: :create_user

  get ':mainslug' => 'main#router', as: 'admin'
  get ':mainslug/visitorinfo/:filter_type' => 'main#visitor_info', as: 'admin_visitor_info'
  get ':mainslug/login' => 'main#router', as: 'admin_index'
  post ':mainslug/login' => 'admin#login_connect', as: 'login_connect'
  get ':mainslug/logout' => 'admin#logout', as: 'admin_logout'
	get ':mainslug/resetpassword' => 'main#resetpassword', as: 'admin_resetpassword_user'
	post ':mainslug/resetpassword' => 'main#resetpassword_submit', as: 'admin_resetpassword_submit_user'
	
  get ':mainslug/pages' => 'pages#index', as: 'admin_page'
  get ':mainslug/pages/add' => 'pages#add', as: 'admin_add_page'
  post ':mainslug/pages/add' => 'pages#create', as: 'admin_create_page'
  get ':mainslug/pages/edit/:id' => 'pages#edit', as: 'admin_edit_page'
  post ':mainslug/pages/edit/:id' => 'pages#update', as: 'admin_update_page'
  post ':mainslug/pages/delete' => 'pages#delete', as: 'admin_delete_page'

  get ':mainslug/categories' => 'categories#index', as: 'admin_category'
  post ':mainslug/categories/add' => 'categories#create', as: 'admin_create_category'
  post ':mainslug/categories/delete' => 'categories#delete', as: 'admin_delete_category'
  get ':mainslug/categories/edit/:id' => 'categories#edit', as: 'admin_edit_category'
  post ':mainslug/categories/edit/:id' => 'categories#update', as: 'admin_update_category'

  get ':mainslug/users' => 'users#index', as: 'admin_user'
  post ':mainslug/users/add' => 'users#add', as: 'admin_add_user'
  get ':mainslug/create-account/:token' => 'users#create_account', as: 'admin_createaccount_user'
  get ':mainslug/users/role' => 'users#role_index', as: 'admin_user_role'
  get ':mainslug/users/role/add' => 'users#add_role', as: 'admin_user_addrole'
  post ':mainslug/users/role/add' => 'users#create_role', as: 'admin_user_createrole'
  get ':mainslug/users/role/edit/:id' => 'users#edit_role', as: 'admin_user_editrole'
  post ':mainslug/users/role/edit/:id' => 'users#update_role', as: 'admin_user_updatetrole'
  post ':mainslug/users/role/delete' => 'users#delete_role', as: 'admin_delete_role'
  get ':mainslug/users/:username' => 'users#profile', as: 'admin_user_profile'
  post ':mainslug/create-account/:token' => 'users#create', as: 'admin_create_user'
  post ':mainslug/users/changerole' => 'users#changerole', as: 'admin_changerole_user'
  post ':mainslug/users/delete' => 'users#delete', as: 'admin_delete_user'
  post ':mainslug/users/changepassword' => 'users#changepassword', as: 'admin_changepassword_user'
  post ':mainslug/users/forgotpassword' => 'main#forgotpassword', as: 'admin_forgotpassword_user'
  
  get ':mainslug/widgets' => 'widgets#index', as: 'admin_widget'
  get ':mainslug/widgets/add' => 'widgets#add', as: 'admin_add_widget'
  post ':mainslug/widgets/add' => 'widgets#create', as: 'admin_create_widget'
  post ':mainslug/widgets/delete' => 'widgets#delete', as: 'admin_delete_widget'
  get ':mainslug/widgets/edit/:id' => 'widgets#edit', as: 'admin_edit_widget'
  post ':mainslug/widgets/edit/:id' => 'widgets#update', as: 'admin_update_widget'

  get ':mainslug/assets' => 'assets#index', as: 'admin_asset'
  get ':mainslug/file_writer/:file_id' => 'assets#file_writer', as: 'admin_asset_filewriter'
  get ':mainslug/template_loader' => 'assets#template_loader', as: 'admin_asset_templateloader'
  post ':mainslug/assets/upload' => 'assets#upload', as: 'admin_assets_upload'
  post ':mainslug/assets/create_dir' => 'assets#create_dir', as: 'admin_assets_create_dir'
  get ':mainslug/assets/edit/:file_id' => 'assets#edit_file', as: 'admin_asset_edit_file'
  post ':mainslug/assets/edit/:file_id' => 'assets#update_file', as: 'admin_asset_update_file'
  get ':mainslug/assets/download/:file_id' => 'assets#download', as: 'admin_asset_download'
  post ':mainslug/assets/delete' => 'assets#delete', as: 'admin_asset_delete'

  get ':mainslug/settings' => 'settings#index', as: 'admin_setting'
  post ':mainslug/settings/update' => 'settings#update', as: 'admin_setting_update'
  post ':mainslug/settings/updatepage' => 'settings#updatepage', as: 'admin_setting_updatepage'
  post ':mainslug/settings/updatesmtp' => 'settings#update_smtp', as: 'admin_setting_updatesmtp'
  
  get ':mainslug/templates' => 'templates#index', as: 'admin_template'
  get ':mainslug/templates/add' => 'templates#add', as: 'admin_add_template'
  post ':mainslug/templates/create' => 'templates#create', as: 'admin_create_template'
  post ':mainslug/templates/delete' => 'templates#delete', as: 'admin_delete_template'
  get ':mainslug/templates/edit/:id' => 'templates#edit', as: 'admin_edit_template'
  post ':mainslug/templates/edit/:id' => 'templates#update', as: 'admin_update_template'

  get ':mainslug/webtraffic' => 'webtraffic#index', as: 'admin_webtraffic'
  get ':mainslug/webtraffic/:id' => 'webtraffic#details', as: 'admin_webtraffic_details'
  
  get ':mainslug/adminactivities' => 'adminactivities#index', as: 'admin_adminactivities'
  
  get ':mainslug/about' => 'about#index', as: 'admin_about'
  
  get '*pagecats/:page' => 'frontpage#index', as: 'frontendpage'
  

end

app/models/role.rb
class Role < ActiveRecord::Base
  
  PERMISSIONS = ["can_view_pages",
    "can_modify_pages",
    "can_view_categories",
    "can_modify_categories",
    "can_view_widgets",
    "can_modify_widgets",
    "can_view_assets",
    "can_modify_assets",
    "can_view_users",
    "can_invite_users",
    "can_modify_users",
    "can_view_roles",
    "can_modify_roles",
    "can_view_settings",
    "can_modify_settings",
    "can_view_templates",
    "can_modify_templates"]
 
  has_many :user
  validates :name, :presence => true, uniqueness: true
  
  def self.search(query)
    if query
      where('name LIKE ?', "%#{query}%")
    else
      all
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :page, :foreign_key => 'created_by'
  belongs_to :role
  has_many :activity

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :fullname, presence: true
  validates :crypted_password, presence: true
  validates :crypted_password, confirmation: true

  validates :username, length: { in: 6..20 }, :allow_blank => true
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }, :allow_blank => true
  validates :crypted_password, length: { minimum: 8 }, :allow_blank => true

  before_create :encrypt_password
  
  PERMISSION_ERROR_MSG = "You don't have permission to perform this action."
  
  def self.login(username, password)
    user = find(:first, :conditions => ['email = ? or username = ?', username, username])
    if user && user.crypted_password == BCrypt::Engine.hash_secret(password, user.password_salt)
    user
    else
      nil
    end
  end

  def encrypt_password
    if crypted_password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.crypted_password = BCrypt::Engine.hash_secret(crypted_password, password_salt)
    end
  end

  def self.search(query)
    if query
      if User.where('fullname LIKE ?', "%#{query}%").take
        where('fullname LIKE ?', "%#{query}%")
      else
        if User.where('username LIKE ?', "%#{query}%").take
          where('username LIKE ?', "%#{query}%")
        else
          where('email LIKE ?', "%#{query}%")
        end
      end
    else
      all
    end 
  end

  def date_joined
    self.created_at.to_time.strftime('%b %d, %Y')
  end

  def username
    self.read_attribute(:username)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	layout :set_layout
	require 'securerandom'
	before_action :require_login, :except => [:create_account, :create]
	before_action :check_admin_slug, :except => [:create_account, :create]

	def index
	  @my_permissions = my_permissions
	  
    if my_permissions.include?("can_view_users")
  	  @admin_slug = admin_backend_slug
  		page = params[:page]
  		search_query = params[:search]
  		@search_keyword = search_query
  		@record_count = User.count
  
  		if params.has_key?(:search)
  			@users = User.search(search_query)
  		else
  			@users = User.page(page).per(15)
  		end
  
  		@roles = Role.all
  		@admin_slug = admin_backend_slug
  
  		if @users.class == Array
  			@users = User.paginate_array(@users).page(page).per(15) 
  		else
  			@users = @users.page(page).per(15)
  		end
  		render 'admin/users/index'
  		
    else
      render 'admin/restricted'
    end
    
	end

	def add
    @my_permissions = my_permissions
		response = Hash.new
    if my_permissions.include?("can_invite_users")
  		@user_request = UserRequest.new()
  		@user_request.email = params[:email]
  		@user_request.role = params[:role]
  		@user_request.token = SecureRandom.hex(32)
  		@user_request.status = "pending"
  		@user_request.save
  
  		if @user_request.errors.any?
  			response["code"] = 201
  			response["message"] = @user_request.errors.full_messages[0]
  		else
  			request_link = root_url + admin_backend_slug + "/create-account/" + @user_request.token
  			# Get the role name base on the role id
  			user_role = Role.find(@user_request.role).name
  			# Send Email to the new user
  			begin
    			UserMailer.send_user_invitation(@user_request.email, request_link, user_role, session[:fullname]).deliver
    			log_user_activities 'invite_user', 'invited <strong>' + params[:email] + ' as ' + user_role + '</strong>'
    			response["code"] = 100
          response["message"] = "Email request has been sent successfully."
  			rescue 
    			response["code"] = 201
          response["message"] = "Error Sending Email. Please check your SMTP settings and try again."
          # Delete Save user_request save
          UserRequest.find_by_email(params[:email]).destroy
        end
  		end
    else
      response["code"] = 201
      response["message"] = [User::PERMISSION_ERROR_MSG]
    end
		render json:response
	end

	def profile
	  @my_permissions = my_permissions
	  @admin_slug = admin_backend_slug
	  @roles = Role.all
		@user = User.find_by_username(params[:username])
		if @user
		  render 'admin/users/profile'
		else
      @title = "User not found"
      @description = 'The user you requested does not exist. <a href="' + admin_user_path + '" >Back to Users</a>'
      @message = @description.html_safe
      render 'admin/extras/404_internal'
		end
	end

	def create_account
	  ##@my_permissions = my_permissions
		user_request = UserRequest.where("token = ? AND status = ?", params[:token], "pending").take
		if user_request
			@user_token = user_request.token
			@user_email = user_request.email
			render 'admin/users/create_account'
		else
			render 'admin/extras/404'
		end
	end

	def delete
    @my_permissions = my_permissions
    if my_permissions.include?("can_modify_users")
  		if can_delete_user(params[:user_ids])
  			# Delete data on user request table
  			params[:user_ids].each do |userid|
  			  user = User.find(userid)
  			  User.find(userid).destroy
  			  UserRequest.find_by_email(user.email).destroy
  			  
          #page_title = Page.find_by_id(item_id).content_title
          #Page.destroy(item_id)
          #Meta.destroy(item_id)
          log_user_activities 'delete_user', 'deleted <strong>' + user.fullname + '</strong>'
  			  
  			  destroy_user_session(user.session_id)
  			end
  		else
  			flash[:error] = "You cannot delete your own account."
  		end
    else
      flash[:error] = User::PERMISSION_ERROR_MSG
    end
		redirect_to admin_user_path
	end

	def create
    #@my_permissions = my_permissions
		user_request = UserRequest.find_by_token(params[:users]["token"])

		if user_request
			@user_token = user_request.token
			@user_email = user_request.email
			@user = User.new(post_create_user_params)
			@user.email = user_request.email
			@user.role_id = user_request.role
			@user.status = "active"
			@user.crypted_password = params[:users]["password"]
			@user.crypted_password_confirmation = params[:users]["password_confirmation"]
			@user.save
			if @user.errors.any?
				@fullname = @user.fullname
				@username = @user.username
				flash.now[:error] = @user.errors.full_messages
				render 'admin/users/create_account'
			else
				user_request.update_attributes(status: 'confirmed')
				login_page_path = root_url + Setting.find_by_setting_name("admin_slug").setting_value
				flash.now[:notice] = 'You have successfully created your account.<br/><a href="' + login_page_path + '">Click here</a> to login your account.'
				session[:user_id] = @user.id
				log_user_activities 'create_account', ' created an account'
				render 'admin/users/create_account'
			end	
		else
			flash.now[:error] = ["Invalid request token"]
			render 'admin/users/create_account'
		end
	end

  def changepassword
    
    input_old_password = params[:oldpassword]
    input_new_password = params[:newpassword]
    
    
    change_user_password = User.find(session[:user_id])
    correct_password = User.login(change_user_password.username, input_old_password)
    response = Hash.new
    
    if correct_password
     
      change_user_password.crypted_password = BCrypt::Engine.hash_secret(input_new_password, change_user_password.password_salt)
      sleep 2
      change_user_password.save
      
      if change_user_password.errors.any?
        response["code"] = 201
        response["message"] = change_user_password.errors.full_messages[0]
      else
        response["code"] = 100
        log_user_activities 'change_password', 'has <strong>change the password</strong>'
        response["message"] = "Your password has been successfully changed."
      end

    else
      response["code"] = 201
      response["message"] = "Please enter correct old password"
    end
     
    render json:response
    
  end

  def changerole
    @my_permissions = my_permissions
    response = Hash.new
      if my_permissions.include?("can_modify_users")
      change_user_role = User.find(params[:userid])
      change_user_role.role_id = params[:role]
      sleep 2
      change_user_role.save
      
      if change_user_role.errors.any?
        response["code"] = 201
        response["message"] = change_user_role.errors.full_messages[0]
      else
        response["code"] = 100
        log_user_activities 'update_user', 'changed <strong>' + change_user_role.fullname + ' role to ' + change_user_role.role.name + '</strong>'
        response["message"] = "User role has been successfully changed."
      end
    else
      response["code"] = 201
      response["message"] = [User::PERMISSION_ERROR_MSG]
    end
    render json:response
  end
  
  def role_index
    @my_permissions = my_permissions
    @admin_slug = admin_backend_slug
    if my_permissions.include?("can_view_roles")
      @roles = Role.all
      page = params[:page]
      search_query = params[:search]
      @search_keyword = search_query
      @record_count = Role.count
  
      if params.has_key?(:search)
        @roles = Role.search(search_query)
      else
        @roles = Role.page(page).per(15)
      end
      
      page = params[:page]
      if @roles.class == Array
        @roles = Role.paginate_array(@roles).page(page).per(15) 
      else
        @roles = @roles.page(page).per(15)
      end
      render 'admin/users/role/index'
    else
      render 'admin/restricted'
    end
  end

  def add_role
    @my_permissions = my_permissions
    @params_role_name = ""
    @params_role_status = "Active"
    @roles = Role::PERMISSIONS
    render 'admin/users/role/add'
  end
  
  def create_role
    @my_permissions = my_permissions
    @roles = Role::PERMISSIONS
    if my_permissions.include?("can_modify_roles")
      role = Role.new
      role.name = params[:role]["name"]
      role.status = params[:role]["status"]
      input_role = params[:permissions]
      role_field = ""
      if !input_role.nil?
      input_role.each do |inputrole|
        role_field += inputrole + ", "
      end
      end
      role.permissions = role_field.chop.chop
      if role.save
        flash[:notice] = "<strong>Role Added!</strong> You've successfully added \"" + role.name + "\"."
        log_user_activities 'create_role', 'created <strong>' + params[:role]["name"] + '</strong> role'
        redirect_to admin_user_role_path
      else
        @params_role_name = role.name
        @params_role_status = role.status.capitalize
        @params_role_permissions = params[:permissions]
        flash.now[:error] = role.errors.full_messages
        render 'admin/users/role/add'
      end
    else
      render 'admin/restricted'
    end
  end
  
  def edit_role
    @my_permissions = my_permissions
    if my_permissions.include?("can_view_roles")
      @roles = Role::PERMISSIONS
      @role = Role.find(params[:id])
      render 'admin/users/role/edit'
    else
      render 'admin/restricted'
    end
  end
  
  def update_role
    @my_permissions = my_permissions
    if my_permissions.include?("can_modify_roles")
      @roles = Role::PERMISSIONS
      @role = Role.find(params[:id])
      if params[:id] != "1"
        role = Role.find(params[:id])
        role.name = params[:role]["name"]
        role.status = params[:role]["status"]
        input_role = params[:permissions]
        role_field = ""
        if not input_role.nil?
          input_role.each do |inputrole|
            role_field += inputrole + ", "
          end
        end
        role.permissions = role_field.chop.chop
        if role.save

app/views/admin/users/role/add.html.erb
<div class="btn-group">
    <a href="<%= admin_user_role_path %>" class="btn"><i class="icon-file"></i> Back to Roles</a>
</div>
<div class="row-fluid">
    <div class="span12">
        <h1>Add Role</h1>
    </div>
</div>
<% if flash[:error] %>
<div class="alert alert-error">
    <% flash[:error].each do |error_message| %>
    <%= error_message %>
    <br />
    <% end %>
</div>
<% end %>

<% if flash[:notice] %>
<div class="alert alert-success mt15">
    <button type="button" class="close" data-dismiss="alert">
        x
    </button>
    <%= flash[:notice].html_safe %>
</div>
<% end %>

<%= form_for :role, url: admin_user_addrole_path, :html => {:name => 'add_role'} do |role_form| %>
<span class="input_label">Role Name</span>
<%= role_form.text_field :name, :class=>"input-block-level", "ng-model"=>"roleName", "ng-init"=>"roleName='"+@params_role_name+"'" %>
            <span class="input_label">Page Status</span>
            <%= role_form.hidden_field :status, :class=>"status", :value=>"{{statusValue.toLowerCase()}}" %>
            <div class="btn-group mb10">
                <a href="javascript:void(0)" class="btn btn-stat btn-large w75 fsize14" ng-init="statusValue='<%= @params_role_status %>'">{{statusValue}}</a>
                <button data-toggle="dropdown" class="btn btn-large dropdown-toggle">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu status-menu">
                    <li>
                        <a href="" ng-click="selectStatus('Active')">Active</a>
                    </li>
                    <li>
                        <a href="" ng-click="selectStatus('Inactive')">Inactive</a>
                    </li>
                </ul>
            </div>
<span class="input_label">Permission</span>
<% if @params_role_permissions.nil? %>
	<% @roles.each do |role| %>
	<label><input type="checkbox" name="permissions[]" value="<%= role %>"> <%= role %></label>
	<% end %>
<% else %>
	<% @roles.each do |role| %>
	<% checkval = @params_role_permissions.include?(role) ? 'checked' : ''  %>
	<label><input type="checkbox" name="permissions[]" value="<%= role %>" <%= checkval %> /> <%= role %></label>
	<% end %>
<% end %>

<div class="btn-holder">
    <%= submit_tag("Save",:class=>"btn btn-primary btn-large mr5") %>
    <a href="<%= admin_user_role_path %>" class="btn btn-large">Cancel</a>
</div>
<% end %>

app/views/admin/users/role/edit.html.erb
<div class="btn-group">
    <a href="<%= admin_user_role_path %>" class="btn"><i class="icon-file"></i> Back to Roles</a>
</div>
<div class="row-fluid">
    <div class="span12">
        <h1>Edit Role</h1>
    </div>
</div>
<% if flash[:error] %>
<div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">
        x
    </button>
    <% flash[:error].each do |error_message| %>
    <%= error_message %>
    <br />
    <% end %>
</div>
<% end %>
<% if flash[:notice] %>
<div class="alert alert-success mt15">
    <button type="button" class="close" data-dismiss="alert">
        x
    </button>
    <%= flash[:notice].html_safe %>
</div>
<% end %>
<% disabled_status = (@role.id == 1 or not @my_permissions.include?("can_modify_roles")) %>
<%= form_for :role, url: admin_user_updatetrole_path, :html => {:name => 'edit_page'} do |role_form| %>
<span class="input_label">Role Name</span>
<% if @role.id != 1  %>
<%= role_form.text_field :name, :class=>"input-block-level", "ng-disabled"=>disabled_status  %>
<% else %>
<%= role_form.text_field :name, :class=>"input-block-level" , "disabled"=>"disabled" %>
<% end %>
            <span class="input_label">Page Status</span>
            <%= role_form.hidden_field :status, :class=>"status", :value=>"{{statusValue.toLowerCase()}}" %>
            <div class="btn-group mb10">
                <a href="javascript:void(0)" class="btn btn-stat btn-large w75 fsize14" ng-init="statusValue='<%= @role.status.capitalize %>'" ng-disabled="<%= disabled_status %>">{{statusValue}}</a>
                <button data-toggle="dropdown" class="btn btn-large dropdown-toggle" ng-disabled="<%= disabled_status %>">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu status-menu">
                    <li>
                        <a href="" ng-click="selectStatus('Active')">Active</a>
                    </li>
                    <li>
                        <a href="" ng-click="selectStatus('Inactive')">Inactive</a>
                    </li>
                </ul>
            </div>
<span class="input_label">Permission</span>
<% @roles.each do |role| %>
<% checkval = @role.permissions.gsub(' ','').split(',').include?(role) ? 'checked' : ''  %>

<label><input type="checkbox" name="permissions[]" value="<%= role %>" <%= checkval %>  ng-disabled="<%= disabled_status %>" > <%= role %></label>
<% end %>
<% if @role.id != 1  %>
    <% if @my_permissions.include?("can_modify_roles") %>
    <div class="btn-holder">
        <%= submit_tag("Update",:class=>"btn btn-primary btn-large mr5") %>
        <a href="<%= admin_user_role_path %>" class="btn btn-large">Cancel</a>
    </div>
    <% end %>
<% end %>
<% end %>

app/views/admin/users/role/index.html.erb
<% if @my_permissions.include?("can_modify_roles") %>
<div class="btn-group">
    <a id="add-user" role="button" class="btn" data-no-turbolink="true" href="<%= admin_user_addrole_path %>" ><i class="icon-plus"></i> Add Role</a>
    <%= link_to raw('<i class="icon-remove"></i> Delete Role(s)'), "javascript:void(0)", id: "delete-users", class: "btn", "ng-click"=>"deleteSelected('#delete_users')", "ng-disabled" => "deleteButton" %>
</div>
<% end %>
<div class="row-fluid">
    <div class="span5">
        <h1>User Role</h1>
    </div>
    <div class="span7">
        <div class="pull-right">
            <div class="input-append">
                <form name="search" method="GET" action="<%= admin_user_role_path %>">
                    <input name="search" class="span9" id="appendedInputButton" type="text" placeholder="Enter Role Name">
                    <button class="btn h40" type="submit">
                        Search
                    </button>
                </form>
            </div>
        </div>
    </div>
    <% if @search_keyword %>
    <div class="mb20">Search Result for <strong>"<%= @search_keyword %>"</strong></div>
    <% end %>
</div>
<% if flash[:error] %>
<div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">
        x
    </button>
    <% flash[:error].each do |error_message| %>
    <%= error_message %>
    <br />
    <% end %>
</div>
<% end %>

<% if flash[:notice] %>
<div class="alert alert-success mt15">
    <button type="button" class="close" data-dismiss="alert">
        x
    </button>
    <%= flash[:notice].html_safe %>
</div>
<% end %>
<a href="<%= admin_user_path %>" class="btn mb20"><i class="icon-user"></i> Back to Users</a>
<% unless @roles.empty?  %>

<% delete_confirm = 'return confirm("Are you sure you want to delete the selected role? \nNote: There\'s no undo.");return false;' %>
<%= form_tag(admin_delete_role_path, :id => 'delete_users', method: "POST", :onsubmit => delete_confirm ) do %>
<table class="table table-striped">
    <thead>
        <tr>
            <% if @my_permissions.include?("can_modify_roles") %>
            <th><%= check_box_tag "role_all", "all", false, :id => "role_all", "ng-model" => "masters", "ng-checked"=>"masterSelect", "ng-click"=>"selectAll(masters," + @roles.count.to_s + ")"  %></th>
            <% end %>
            <th>ID</th>
            <th>Name</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        <% @roles.each do |role| %>
        <tr>
            <% if @my_permissions.include?("can_modify_roles") %>
            <td><%= check_box_tag "role_ids[]", role.id, false, :class => 'checkbox_item', :id => "role_#{role.id}", "ng-model"=>"role"+role.id.to_s, "ng-checked" => role.id == 1 ? '' : "masters","ng-click"=>"selectItem(role"+role.id.to_s+")","ng-disabled" => role.id == 1 ? 'true' : 'false' %></td>
            <% end %>
            <td><%= role.id %></td>
            <td><%= link_to role.name, admin_user_editrole_path(@admin_slug, role.id), 'data-no-turbolink' => true  %></td>
            <% if role.status == 'active' %>
            <td><span class="label label-success"><%= role.status %></span> </td>
            <% else %>
             <td><span class="label"><%= role.status %></span> </td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>
<% end %>
<div class="pull-right">
    <%= paginate @roles %>
</div>
<div style="clear:both"></div>
<% else %>
<% if @record_count > 0  %>
<p>
    No results were found for your request! <a href="<%= admin_user_role_path %>">Back to Roles.</a>
</p>
<% else %>
<p>
    You have not created any role. <a href="<%= admin_user_addrole_path %>">create now?</a>
</p>
<% end %>
<% end %>